name: Create Application Gateway

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
    - "bicep/**"
    - ".github/workflows/infra.yml"

jobs:
  create-azure-resources:

    env:
      DEPLOYMENT_NAME: appgw-deployment
      SPOKE_RG_NAME: 'rg-spoke-ase-demo'
      LOCATION: 'eastus' # You can change this to reflect the region where you deploy your ASE

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Validate that bicep builds
        run: az bicep build -f gateway.bicep
        working-directory: ./bicep

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}          
          resourceGroupName: ${{ env.SPOKE_RG_NAME}} 
          deploymentName:  ${{ env.DEPLOYMENT_NAME }}
          template: ./bicep/gateway.json
          parameters: gwSubnetId=${{ secrets.GATEWAY_SUBNET_ID }} certLink=${{ secrets.CERTIFICATE_URL }} location=${{ env.LOCATION }} weatherApiFQDN=${{ secrets.WEBAPP_FQDN }} customDomainWeatherApiFQDN=${{ secrets.CUSTOM_DOMAIN_WEATHER_API }} identityId=${{ secrets.GATEWAY_USER_ASSIGNED_ID }}


    
