name: Create Azure Resources

on:
  workflow_dispatch:    
  push:
    branches:
    - main
   
    paths:
    - bicep/**    
    - .github/workflows/infra.yml

jobs:
  create-azure-resources:

    env:
      DEPLOYMENT_NAME: ase-deployment
      REGION: 'eastus' # You can change this to reflect the region where you deploy your ASE

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Validate that bicep builds
        run: az bicep build -f main.bicep
        working-directory: ./bicep

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ env.REGION }}
          deploymentName:  ${{ env.DEPLOYMENT_NAME }}
          template: ./bicep/main.bicep
          parameters: ./bicep/main.parameters.json

      - uses: gliech/create-github-secret-action@v1
        name: Write Web App Name
        with:
          name: WEBAPP_NAME
          value: ${{ steps.createResources.outputs.webappname }}
          pa_token: ${{ secrets.PA_TOKEN }}          

      - uses: gliech/create-github-secret-action@v1
        name: Write Vault Name
        with:
          name: VAULT_NAME
          value: ${{ steps.createResources.outputs.vaultName }}
          pa_token: ${{ secrets.PA_TOKEN }}                


    
