name: Create Azure Resources

on:
  workflow_dispatch:    
  push:
    branches:
    - main
   
    paths:
    - bicep/**    
    - .github/workflows/infra.yml

jobs:
  create-azure-resources:

    env:
      DEPLOYMENT_NAME: ase-deployment
      REGION: 'eastus' # You can change this to reflect the region where you deploy your ASE

    runs-on: ubuntu-latest

    outputs:
      webAppFQDN: ${{ steps.createResources.outputs.webAppFQDN }}
      gatewaySubnetId: ${{ steps.createResources.outputs.gatewaySubnetId }}
      gwIdentityId: ${{ steps.createResources.outputs.gwIdentityId }}
      spokeResourceGroupName: ${{ steps.createResources.outputs.spokeResourceGroupName }}

    steps:
      
      - uses: actions/checkout@v2

      - name: Validate that bicep builds
        run: az bicep build -f main.bicep
        working-directory: ./bicep

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Convert to ARM
        run: |
          bicep build ./bicep/main.bicep 

      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ env.REGION }}
          deploymentName:  ${{ env.DEPLOYMENT_NAME }}
          template: ./bicep/main.json
          parameters: ./bicep/main.parameters.json adminUsername=${{ secrets.VM_USERNAME }} adminPassword=${{ secrets.VM_PASSWORD }}

      - uses: gliech/create-github-secret-action@v1
        name: Write Web App Name
        with:
          name: WEBAPI_WEATHER_NAME
          value: ${{ steps.createResources.outputs.webappname }}
          pa_token: ${{ secrets.PA_TOKEN }}

  create-application-gateway:
    environment:
      name: PROD
    needs: create-azure-resources
    runs-on: ubuntu-latest

    env:      
      DEPLOYMENT_NAME: appgw-deployment
      REGION: 'eastus'

    steps:

      - uses: actions/checkout@v2

      - name: deploy application gateway        
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}          
          resourceGroupName: ${{ needs.create-azure-resources.outputs.spokeResourceGroupName }} 
          region: ${{ env.REGION }}
          deploymentName:  ${{ env.DEPLOYMENT_NAME }}
          template: ./bicep/gateway.bicep
          parameters: gwSubnetId=${{ needs.create-azure-resources.outputs.gatewaySubnetId }} certLink=${{ secrets.CERTIFICATE_URL }} location=${{ env.REGION }} weatherApiFQDN=${{ needs.create-azure-resources.outputs.webAppFQDN }} customDomainWeatherApiFQDN=${{ secrets.CUSTOM_DOMAIN_WEATHER_API }} identityId=${{ needs.create-azure-resources.outputs.gwIdentityId }}
                        


    
