name: Deploy Weather Api

on:
  workflow_dispatch:

  # push:
  #   branches:
  #   - main
   
  #   paths:
  #   - src/WeatherApi/**    
  #   - .github/workflows/weather-api.yml  

env:
  AZURE_WEBAPP_DIRECTORY: ./src/WeatherApi
  AZURE_WEBAPP_PACKAGE_PATH: package


jobs:

  build-web-api:

    runs-on: self-hosted
    
    steps:

      - uses: actions/checkout@v2

      - name: Setup Dotnet 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        working-directory: ${{ env.AZURE_WEBAPP_DIRECTORY }}

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure webapp deploy'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ secrets.WEBAPI_WEATHER_NAME }}         
          package: '${{ env.AZURE_WEBAPP_DIRECTORY}}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
